"""Generates reports/eda.md — the descriptive statistics behind the README.

Run: python -m src.eda

Everything here is computed on the training set for *description only*. No
value produced by this module is used to fit anything; all fitting happens
inside CV folds in `validation.run_cv`.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

from .data import CATEGORICAL_COLS, NUMERIC_COLS, TARGET, load_train

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "reports" / "eda.md"


def univariate_auc(X: pd.DataFrame, y: np.ndarray) -> pd.DataFrame:
    """AUC of each numeric feature used alone as a score.

    Computed on the rows where the feature is present, so it measures the
    feature's own ranking power without confounding it with missingness.
    Values below 0.5 mean the feature ranks in the opposite direction; what
    matters is the distance from 0.5, so `|AUC - 0.5|` is reported too.
    """
    rows = []
    for col in NUMERIC_COLS:
        present = X[col].notna().to_numpy()
        auc = roc_auc_score(y[present], X.loc[present, col])
        rows.append(
            {
                "feature": col,
                "n_present": int(present.sum()),
                "auc": round(float(auc), 5),
                "abs_lift": round(abs(float(auc) - 0.5), 5),
            }
        )
    return pd.DataFrame(rows).sort_values("abs_lift", ascending=False)


def missingness_table(X: pd.DataFrame, y: np.ndarray) -> pd.DataFrame:
    """Missing rate per column, plus the target rate among missing vs present.

    If missingness were informative, these two target rates would differ.
    """
    base = y.mean()
    rows = []
    for col in X.columns:
        na = X[col].isna().to_numpy()
        rows.append(
            {
                "feature": col,
                "missing_pct": round(100 * na.mean(), 2),
                "target_rate_missing": round(float(y[na].mean()), 4) if na.any() else np.nan,
                "target_rate_present": round(float(y[~na].mean()), 4),
                "delta": round(float(y[na].mean() - y[~na].mean()), 4) if na.any() else np.nan,
            }
        )
    out = pd.DataFrame(rows).sort_values("missing_pct", ascending=False)
    out.attrs["base_rate"] = base
    return out


def categorical_table(X: pd.DataFrame, y: np.ndarray) -> pd.DataFrame:
    rows = []
    for col in CATEGORICAL_COLS:
        vals = X[col].fillna("(missing)")
        for level, idx in vals.groupby(vals).groups.items():
            mask = vals.index.isin(idx)
            rows.append(
                {
                    "feature": col,
                    "level": level,
                    "count": int(mask.sum()),
                    "share_pct": round(100 * mask.mean(), 2),
                    "target_rate": round(float(y[mask].mean()), 4),
                }
            )
    return pd.DataFrame(rows)


def main() -> None:
    X, y = load_train()
    REPORT.parent.mkdir(parents=True, exist_ok=True)

    miss = missingness_table(X, y)
    uni = univariate_auc(X, y)
    cats = categorical_table(X, y)
    desc = X[NUMERIC_COLS].describe().T.round(3)

    parts = [
        "# EDA — Playground S6E8",
        "",
        "Generated by `python -m src.eda`. Descriptive only; nothing here is fit "
        "outside a CV fold.",
        "",
        "## Shape",
        "",
        f"- Training rows: **{len(X):,}**",
        f"- Features: **{len(NUMERIC_COLS)} numeric, {len(CATEGORICAL_COLS)} categorical**",
        f"- Positive rate (`{TARGET}` = 1): **{y.mean():.4f}**",
        "",
        "## Numeric feature summary",
        "",
        desc.to_markdown(),
        "",
        "## Missingness",
        "",
        "Every feature has missing values. `delta` is the difference in target "
        "rate between rows where the feature is missing and rows where it is "
        "present — if missingness carried signal, these would separate.",
        "",
        miss.to_markdown(index=False),
        "",
        "## Univariate AUC (numeric features, alone)",
        "",
        uni.to_markdown(index=False),
        "",
        "## Categorical levels",
        "",
        cats.to_markdown(index=False),
        "",
    ]
    REPORT.write_text("\n".join(parts))
    print(f"wrote {REPORT}")
    print(f"\nbase rate {y.mean():.4f}")
    print("\nlargest |target-rate delta| by missingness:")
    print(miss.reindex(miss["delta"].abs().sort_values(ascending=False).index).head(5).to_string(index=False))
    print("\ntop univariate AUCs:")
    print(uni.head(5).to_string(index=False))


if __name__ == "__main__":
    main()
